name: brierley
favicon: null
layout_spectrum: 1
typography_spectrum: 0.84396
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0c0c0c'
    - '#c3c3c3'
    - '#494949'
    - '#808080'
    - '#fdfdfd'
  brandStrength: 0.875
  lightness: 0.5129738308023661
  saturation: 0.7336475213523954
  rhythmicContrast: 0.9938598012086004
purpose: []
